"""
Function to generate buttons for documentation.

Long lines in HTML strings are intentional for readability and maintainability.
PEP-8 line length is ignored in these sections.

Acknowledgements
----------------
Some parts of this module were generated by and adapted from Perplexity.
"""


def generate_html(pypi_url, github_url, conda_url=None, include_conda=True):
    """
    Generate HTML buttons with icons for PyPI, GitHub, and (optionally) Conda.

    Parameters
    ----------
    pypi_url : str
        The URL to the project's PyPI page.
    github_url : str
        The URL to the project's GitHub repository.
    conda_url : str, optional
        The URL to the project's Conda page (default is None).
    include_conda : bool, optional
        If True and `conda_url` is provided, include the Conda button (default is True).

    Returns
    -------
    str
        An HTML string containing the buttons with icons.

    Notes
    -----
    Adapted from code generated by Perplexity.
    """
    html = f"""
<div style="display: flex; gap: 1em; margin-bottom: 1em;">
  <a href="{pypi_url}" target="_blank" style="text-decoration: none;">
    <span style="display: inline-flex; align-items: center; background: #3775A9; color: #fff; border-radius: 20px; padding: 0.4em 1em; font-weight: 600; gap: 0.5em;">
      <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/pypi.svg" alt="PyPI" width="20" height="20" style="filter: brightness(0) invert(1);" />
      View on PyPI
    </span>
  </a>
  <a href="{github_url}" target="_blank" style="text-decoration: none;">
    <span style="display: inline-flex; align-items: center; background: #000; color: #fff; border-radius: 20px; padding: 0.4em 1em; font-weight: 600; gap: 0.5em;">
      <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg" alt="GitHub" width="20" height="20" style="filter: brightness(0) invert(1);" />
      View on GitHub
    </span>
  </a>
"""
    if include_conda and conda_url:
        html += f"""
  <a href="{conda_url}" target="_blank" style="text-decoration: none;">
    <span style="display: inline-flex; align-items: center; background: #3EB049; color: #fff; border-radius: 20px; padding: 0.4em 1em; font-weight: 600; gap: 0.5em;">
      <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/anaconda.svg" alt="Conda" width="20" height="20" style="filter: brightness(0) invert(1);" />
      View on Conda
    </span>
  </a>
"""
    html += "</div>"
    return html
