<hr style="height:0pt; visibility:hidden;" />

# ruff

Modern, ultra-fast linter that implements checks from Flake8 and some other popular plugins.

Running `lintquarto -l ruff` will run `ruff check`, a read-only linter. For ruff-based code rewriting commands (`ruff format` and `ruff check --fix`), please see the [ruff formatter page](ruff_format.qmd).

```{python}
#| echo: false
# Import required packages
import subprocess
import sys

# Add parent directory to sys.path
sys.path.insert(0, "..")

# Import the helper functions
from helpers import generate_html, print_quarto
```

```{python}
#| echo: false
#| output: asis
generate_html(
    pypi_url="https://pypi.org/project/ruff/",
    github_url="https://github.com/astral-sh/ruff",
    conda_url="https://anaconda.org/conda-forge/ruff"
)
```

## Example Quarto `.qmd` file:

{{< downloadthis examples/general_example.qmd dname="general_example" label="Download the example" type="light" >}}

:::{.pale-grey}
```{python}
#| echo: false
print_quarto("examples/general_example.qmd")
```
:::

## Run ruff using `lintquarto`

```{.bash}
lintquarto -l ruff -p general_example.qmd
```

:::{.pale-green}
<style>
.cell-output-stdout code {
  word-break: break-word !important;
  white-space: pre-wrap !important;
}
</style>
```{python}
#| echo: false
result = subprocess.run(
    [
        sys.executable,
        "-m",
        "lintquarto",
        "-l",
        "ruff",
        "-p",
        "examples/general_example.qmd"
    ],
    capture_output=True,
    text=True,
    check=False
)
print(result.stdout)
```
:::

## Notes

### Excluded checks

The check [RUF100](https://docs.astral.sh/ruff/rules/unused-noqa/) is disabled by default due to conflicts with the manner in which lintquarto acts, leading to false positives if this check is enabled. More details on this decision can be found in [this GitHub issue](https://github.com/lintquarto/lintquarto/issues/120).

The check [INP001](https://docs.astral.sh/ruff/rules/implicit-namespace-package/) is also disabled by default due to the majority of quarto documents not having an `__init__.py` file in their directory. More details on this can be found in [this GitHub issue](https://github.com/lintquarto/lintquarto/issues/141).
