project:
  type: website
  output-dir: _site

format:
  html:
    theme: minty

website:
  title: "lintquarto"
  description: "Documentation for the lintquarto python package"
  repo-url: https://github.com/lintquarto/lintquarto
  page-navigation: true
  navbar:
    pinned: true
    search: true
    left:
      - get_started.qmd
      - user_guide.qmd
      - api/index.qmd
      - text: Contributing
        href: contributing.qmd
      - text: Changelog
        href: changelog.qmd
    right:
      - icon: github
        href: https://github.com/lintquarto/lintquarto
        aria-label: lintquarto GitHub

metadata-files:
  - api/_sidebar.yml

quartodoc:
  title: Reference
  dir: api
  out_index: index.qmd
  package: lintquarto
  sections:
    - title: Main module
      desc: "The main CLI logic for linting Python code in Quarto (`.qmd`) files, including argument parsing, file conversion, linter invocation, and temporary file management."
      package: lintquarto.__main__
      contents:
        - process_qmd
        - gather_qmd_files
        - main
    - title: Converter module
      desc: "Functions to convert Quarto (`.qmd`) files to Python (`.py`) files, preserving line alignment and extracting Python code, with both a command-line interface and callable functions."
      package: lintquarto.converter
      contents:
        - _qmd_lines_to_py_lines
        - convert_qmd_to_py
    - title: Linters module
      desc: "Class to check for supported and available Python linters or static type checkers on the user's system."
      package: lintquarto.linters
      contents:
        - Linters
    - title: Args module
      desc: "Class which extends `argparse.ArgumentParser` to provide user-friendly error messages and help text when incorrect command-line arguments are supplied."
      package: lintquarto.args
      contents:
        - CustomArgumentParser