name: lint
run-name: Lint package and documentation

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Python from .python-version
        uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Sync project from uv.lock
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff check on package
        run: uv run ruff check .
      
      - name: Run Ruff check on code in documentation
        run: uv run lintquarto -l ruff -p docs